### ISSUE TITLE
[Bug] ... Texts are completely broken

### ISSUE THREAD

**Issue by hep3yull** [SuperMartijn642/OreGrowth#29] opened 2024-09-27 04:34 UTC
Version Info
- Minecraft 1.20.1
- Ore Growth 1.1.2

What mod loader are you using? : Fabric 0.16.5

Description of the Bug
Since updating to 1.1.2 all text in the game has been completely broken and everything looks □
Also if I open the world, the game crashes
+ I noticed the same issue in 1.1.1b. The text appears normally in 1.1.1a

Steps to Reproduce
This will definitely happen if version 1.1.2 of Ore Growth enabled, but not if disabled

Screenshots
![2024-09-27_13 24 45](https://github.com/user-attachments/assets/7fdbd63d-1053-4e29-bf43-8a6434450977)

**Comment by SuperMartijn642** [comment] 2024-09-27 06:08
I don't think this is caused by Ore Growth. This is usually caused by whatever launcher not providing the assets arguments correctly to the game.

Can you share the `logs/latest.log`?

**Comment by hep3yull** [comment] 2024-09-27 09:36
[latest.log](https://github.com/user-attachments/files/17162204/latest.log)

**Comment by SuperMartijn642** [comment] 2024-09-27 09:57
Thank you, sadly the log has thousands of lines of spam from random mods, so can't really get anything from it.
Are you sure this is caused by Ore Growth? Does the issue go away if you just disable Ore Growth and keep all other mods?
Is the issue present with just Ore Growth installed? If not, can you narrow down which other mods are needed to reproduce the issue?

**Comment by hep3yull** [comment] 2024-09-28 03:31
In my modpack, there are no issues even with all other mods enabled except Ore Growth. I confirmed that this does not happen if only Ore Growth is installed

**Comment by hep3yull** [comment] 2024-09-28 03:31
And I think I found the cause of the problem probably a conflict with Sodium. This is the log when only Sodium and Ore Growth are enabled
[latest.log](https://github.com/user-attachments/files/17172134/latest.log)

**Comment by SuperMartijn642** [comment] 2024-09-28 09:05
Hmm very odd, thanks for looking into it.
Not entirely sure, but could you try installing Indium?  Sodium replaces the vanilla rendering with their own which breaks the Fabric Rendering API. Indium patches Sodium to support the Fabric Rendering API.
Haven't seen anything like this before resulting from it though

**Comment by hep3yull** [comment] 2024-09-29 03:15
Installed Indium and no issues occurred, I'm sure it's a problem with Sodium

**Comment by SuperMartijn642** [comment] 2024-10-01 18:16
I will close the issue then as there's not much I can do about it on my end.

**Closed as completed by SuperMartijn642** 2024-10-01 18:16 UTC
Labels: bug
