### ISSUE TITLE
[Bug] Only iron ore textures used

### ISSUE THREAD

**Issue by TheBiggestHuman** [SuperMartijn642/OreGrowth#23] opened 2024-06-09 16:45 UTC
**Version Info**
- Minecraft 1.20.1
- Ore Growth 1.0.11
- ModernFix 5.8.1 or 5.17.0
- Continuity 3.0.0-beta.4 or 3.0.0-beta.5

**What mod loader are you using?**: Fabric 0.14.23 (Fabulously Optimized 5.4.1 modpack) or Fabric 0.15.11 (Simply Optimized  1.20.1-12.0 modpack)

**Description of the Bug**
Ore clusters only have iron textures if _mixin.perf.model_optimizations_ in ModernFix is **not** set to false and/or Continuity is installed. 

I have listed both Fabulously Optimized and Simply Optimized as I have tested both, and because it's easier to reproduce. Indium is already installed in both modpacks. Simply Optimised has an altered ModernFix config, removing all of the tweaks and setting model optimizations to false fixes it. 

A bit unrelated, Polytone works as a slight replacement to Continuity, however, ore clusters cannot be placed and break immediately when any block around it changes in any way, but the texture works.

Thank you!

**Steps to Reproduce**
1. Install either Fabulously Optimized or Simply Optimized
2. Install Ore Growth and its dependencies
3. Place any ore block except for iron
4. Place an ore cluster item
5. Iron ore cluster!

**Screenshots**
![Screenshot_20240609_173135](https://github.com/SuperMartijn642/OreGrowth/assets/171545539/9675091f-7810-4d43-9e4d-429f0b44864b)

**Comment by SuperMartijn642** [comment] 2024-08-24 10:47
> Ore clusters only have iron textures if mixin.perf.model_optimizations in ModernFix is not set to false and/or Continuity is installed.

Only with ModernFix 5.8.1, do the crystals not take on the look of the block they are on. Even with both ModernFix 5.17.0 and Continuity 3.0.0-beta.5 or 3.0.0-beta.4 installed, the crystals from Ore Growth have the correct texture for the block they're on.
Thus, it appears to have been a ModernFix issue which has been fixed.

> A bit unrelated, Polytone works as a slight replacement to Continuity, however, ore clusters cannot be placed and break immediately when any block around it changes in any way, but the texture works.

Everything appears to work fine with Polytone installed.

Closing this as the issues seem to have been caused by other mods and since have been fixed.

**Closed as completed by SuperMartijn642** 2024-08-24 10:47 UTC
Labels: bug
